name: atlasweather
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  flutter_spinkit: ^5.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  http: ^0.13.3
  line_icons: ^2.0.1
  extended_image: ^4.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: fonts/josefinSans/JosefinSans-Bold.ttf
        - asset: fonts/josefinSans/JosefinSans-BoldItalic.ttf
        - asset: fonts/josefinSans/JosefinSans-ExtraLight.ttf
        - asset: fonts/josefinSans/JosefinSans-ExtraLightItalic.ttf
        - asset: fonts/josefinSans/JosefinSans-Italic.ttf
        - asset: fonts/josefinSans/JosefinSans-Light.ttf
        - asset: fonts/josefinSans/JosefinSans-LightItalic.ttf
        - asset: fonts/josefinSans/JosefinSans-Medium.ttf
        - asset: fonts/josefinSans/JosefinSans-MediumItalic.ttf
        - asset: fonts/josefinSans/JosefinSans-Regular.ttf
        - asset: fonts/josefinSans/JosefinSans-SemiBold.ttf
        - asset: fonts/josefinSans/JosefinSans-SemiBoldItalic.ttf
        - asset: fonts/josefinSans/JosefinSans-Thin.ttf
        - asset: fonts/josefinSans/JosefinSans-ThinItalic.ttf